targets:
  $default:
    builders:
      slang_build_runner:
        options:
          input_directory: assets/lang
          output_directory: lib/src/assets/lang
          namespaces: true
          input_file_pattern: .json
          output_file_name: translations.g.dart
          output_format: multiple_files
          locale_handling: true
          flutter_integration: true
          base_locale: tr
          fallback_strategy: base_locale
          string_interpolation: dart
          translate_var: t
          enum_name: AppLocale
          class_name: Translations
          translation_class_visibility: private
          key_case: snake
          key_map_case: camel
          param_case: pascal
          flat_map: false
          translation_overrides: false
          timestamp: true
          statistics: true
