blank_issues_enabled: false
contact_links:
  - name: Flutter Common Resources Readme
    url: https://github.com/bahricanyesil/flutter-common-resources/blob/main/README.md
    about: You can see the details of the repository here.
